### ISSUE TITLE
Error when opening Data Explorer

### ISSUE THREAD

**Issue by gerhardvdw65** [tabulartools/pbi-explorer#12]
### Describe the problem

Get an unhandled exception when clicking on the Data Model Explorer tab.

### Power BI

Get an Unhandled Exception when using the Data Model Explorer on a model that actually opened in PBIExplorer

### Additional context

![image](https://github.com/tabulartools/pbi-explorer/assets/15626119/0bf8b9fb-45fc-4047-9e70-30d3599a1d26)

### Anything else ?

[Data Explorer Bug.txt](https://github.com/tabulartools/pbi-explorer/files/12706193/Data.Explorer.Bug.txt)

**Comment by DBojsen** [comment]
Hi @gerhardvdw65 

Could you click on the details button and paste a screenshot of the full error message?

BR David - Tabular Tools

**Comment by DBojsen** [comment]
Hi again @gerhardvdw65 

Sorry, I missed the attached file - we have what we need.

BR David - Tabular Tools

**Comment by ackerk** [comment]
Had the exact same error message when clicking on the tab 'Data Model Explorer'.

**Comment by DBojsen** [comment]
This have been fixed in version 0.3.1 (Beta2).  Please update by downloading the new version at www.PBIExplorer.com.
Thanks for reporting.
