### ISSUE TITLE
Unable to open PbiExplorer, .NET 7 is not installed

### ISSUE THREAD

**Issue by nassaubv** [tabulartools/pbi-explorer#13]
### Describe the problem

I am not able to install .NET 7 on my laptop due to lack of admin rights. The release notes mentions I would not need it preinstalled, but it seems not to be the case.

### Power BI

Power BI Desktop Sep 2023

### Steps to reproduce the behavior

1. Click on PbiExplorer.exe

### Screenshots

![image](https://github.com/tabulartools/pbi-explorer/assets/145527448/6e148f2c-4466-4ef4-aaec-5759ef017b4d)

**Comment by DBojsen** [comment]
Hi @nassaubv 

Thank you for reporting - we'll investigate and return.

BR David - Tabular Tools

**Comment by jonathannavarrop** [comment]
Same issue here with .NET

Regards,
Jonathan NP

**Comment by DBojsen** [comment]
Hi @nassaubv & @jonathannavarrop 

Could I ask which version of Windows you are using - like this screenshot:
![image](https://github.com/tabulartools/pbi-explorer/assets/22237520/60c807e3-ff5e-4a3e-b0e1-d945d0cee690)

**Comment by DBojsen** [comment]
We found the issue and will push an update hopefully today

**Comment by DBojsen** [comment]
This have been fixed in version 0.3.1 (Beta2).  Please update by downloading the new version at www.PBIExplorer.com.
Thanks for reporting.
