### ISSUE TITLE
Analyze Report and Guided Tour Greyed out

### ISSUE THREAD

**Issue by minasihene** [tabulartools/pbi-explorer#17]
### Describe the problem

Unable to explore Analyze report and Guided tour tabs

### Power BI

Power BI Desktop version September 2023

### Steps to reproduce the behavior

Open PBI Explorer

### Screenshots

![Screenshot 2023-09-25 031952](https://github.com/tabulartools/pbi-explorer/assets/66710207/ce1524b3-90fe-4357-a4ae-560a91630ed0)

**Comment by DBojsen** [comment]
Hi @minasihene 

That’s because they are not in the product yet. 
Will be added in a later beta release. 

Please read the release notes, where this (+ more) is explained. 

BR David - Tabular Tools
