### ISSUE TITLE
Unable to detect columns in both reports

### ISSUE THREAD

**Issue by minasihene** [tabulartools/pbi-explorer#18]
### Describe the problem

The tool could not detect the columns in first report and was able to detect only 2 columns in the second report.
Both reports contain 16 columns

report 1 contains 3 measures, 2 of them were identified,
report 2 contains contains 3 measures, none of them were identified

Report 1 measures used in report was identified as "False"

### Power BI

Power BI Desktop version September 2023

### Steps to reproduce the behavior

Open PBI Explorer
Choose Compare Report
Expand Data Model

### Screenshots

![image](https://github.com/tabulartools/pbi-explorer/assets/66710207/2b1af72e-8b7d-4241-903e-77062deb4081)

**Comment by DBojsen** [comment]
Hi @minasihene 

In the screenshot you are only seeing objects with changes. 
This is the default view for the comparer. 

You can use the drop-down (Refine comparion) to change what you see - including unmodified objects. 

BR David - Tabular Tools

**Comment by minasihene** [comment]
Thanks

**Comment by DBojsen** [comment]
Also, the data model shown here is only the conceptual data model. 
It is not the actual data model (yet), but only the objects that are in use by report elements.
