### ISSUE TITLE
We couldn't open the specified file.

### ISSUE THREAD

**Issue by theunisja** [tabulartools/pbi-explorer#20]
### Describe the problem

Error when opening PBIX file, see screenshot.

### Power BI

Version: 2.121.762.0 64-bit (September 2023)

### Steps to reproduce the behavior

In both Report Inspector & Report Comparer, I get this error message when opening my report. As far as I know, this is not report does not use any exotic features.

### Screenshots

![image](https://github.com/tabulartools/pbi-explorer/assets/713363/b37e166b-ef68-495a-989b-5d4b587a72d6)

**Comment by DBojsen** [comment]
Hi @Jappejynx 

Just making sure - you didn’t copy the EXE file somewhere outside the folder before running it?
(It is dependent of the other files included in the zip)

**Comment by theunisja** [comment]
Hi @DBojsen ,

No, extracted the ZIP file and did not touch any of the files. I am able to load some other PBIX files though. 

Below a similar error message when opening another report:

![image](https://github.com/tabulartools/pbi-explorer/assets/713363/97c06d8f-db0d-4428-8180-f6ca595ab809)

**Comment by akruzel1932** [comment]
I'm having the same issue as above.  A lot of this has ".ReportModel" in the message.  My report has a live connection to a PBI dataset.  Can this tool work this way or does it need to have a dataset?

**Comment by paul-vandyck** [comment]
> I'm having the same issue as above. A lot of this has ".ReportModel" in the message. My report has a live connection to a PBI dataset. Can this tool work this way or does it need to have a dataset?

It appears to support reports connected to a dataset, because one report I have opens.

6 others i have do not.    We don't use anything exotic.     These are the error messages...

![image](https://github.com/tabulartools/pbi-explorer/assets/146133576/daf84430-553f-48e9-9297-c3e9ec88d814)
![image](https://github.com/tabulartools/pbi-explorer/assets/146133576/b3699776-b1a1-4fc3-bb87-ce79bcf4a95e)

**Comment by DBojsen** [comment]
> I'm having the same issue as above. A lot of this has ".ReportModel" in the message. My report has a live connection to a PBI dataset. Can this tool work this way or does it need to have a dataset?

It only needs a report definition.

**Comment by DBojsen** [comment]
> > I'm having the same issue as above. A lot of this has ".ReportModel" in the message. My report has a live connection to a PBI dataset. Can this tool work this way or does it need to have a dataset?
> 
> It appears to support reports connected to a dataset, because one report I have opens.
> 
> 6 others i have do not. We don't use anything exotic. These are the error messages...
> 
> ![image](https://user-images.githubusercontent.com/146133576/270783784-daf84430-553f-48e9-9297-c3e9ec88d814.png) ![image](https://user-images.githubusercontent.com/146133576/270783857-b3699776-b1a1-4fc3-bb87-ce79bcf4a95e.png)

These are duplicates of #3 and not related to this issue

**Comment by DBojsen** [comment]
> Hi @DBojsen ,
> 
> No, extracted the ZIP file and did not touch any of the files. I am able to load some other PBIX files though.
> 
> Below a similar error message when opening another report:
> 
> ![image](https://user-images.githubusercontent.com/713363/270370173-97c06d8f-db0d-4428-8180-f6ca595ab809.png)

This is a separate issue - I have created bugs for both

**Comment by DBojsen** [comment]
This have been fixed in version 0.3.1 (Beta2).  Please update by downloading the new version at www.PBIExplorer.com.
Thanks for reporting.
