### ISSUE TITLE
Get specification from Power BI Service using XMLA endpoint

### ISSUE THREAD

**Issue by morelgeorge** [tabulartools/pbi-explorer#22]
### The feature request

Currently we are able to connect directly to a local report file. However it could be useful to connect directly to a Power BI Service using XMLA endpoint. 

In Power BI there is no really easy way how to open / compare report specification. I believe this tool is really close! :-) 

### Proposed solution

When opening a file, there could be a possibility to choose whether I want to open local report specification or I want to connect to a Power BI Service using XMLA endpoint.

**Comment by mthierba** [comment]
The XMLA endpoint only allows access to Power BI datasets. However, some new Fabric APIs were announced recently (they're not yet available) which will ultimately enable what you're asking for. It's something we can consider once the APIs are released.
