### ISSUE TITLE
Error while opening a pbix connected to AAS in Live Connection

### ISSUE THREAD

**Issue by fahadkhan2306** [tabulartools/pbi-explorer#28]
### Describe the problem

As I Open the pbix which is connected to AAS in live connection mode getting below error

<img width="557" alt="image" src="https://github.com/tabulartools/pbi-explorer/assets/51118866/e3f30b9e-f203-40a4-b665-75e423f85420">

### Power BI

PowerBI Desktop Version: 2.122.325.0 64-bit (October, 2023), Azure Analysis Services

### Windows

Windows 11 Enterprise

### Screenshots

<img width="557" alt="image" src="https://github.com/tabulartools/pbi-explorer/assets/51118866/a7241a84-cc68-4ee9-975e-dcbee2b97db4">

**Comment by DBojsen** [comment]
Hi @fahadkhan2306 

Does your report have sesitivity labels enabled?

**Comment by fahadkhan2306** [comment]
Yes, I have - "Confidential"

**Comment by DBojsen** [comment]
Ok, we have unfortunately learnt that this is a limitation with sensitivity labels.
When used, the pbix is no longer a regular pbix, but in a format we cannot read.

We'll work on handling this gracefully, but unless something changes in the format, we are unable to provide any help with pbix's that have sensitivity labels enabled.

**Comment by fahadkhan2306** [comment]
Hi @DBojsen Got it, thanks for checking. As a workaround I have removed the sensitivity labels & it worked.

**Comment by DBojsen** [comment]
This has now been fixed in BETA3.
You can download this version here [https://pbiexplorer.com](https://pbiexplorer.com).

Thank you for reporting.
