### ISSUE TITLE
Unable to open any .pbix files within PbiExplorer

### ISSUE THREAD

**Issue by jhartranft** [tabulartools/pbi-explorer#3]
### Describe the problem

Regardless of the file I choose in Inspector, I get a pop-up error window stating "Error opening file" and "We couldn't open the specified file. Most likely, the file contains a feature not yet supported by PBI Explorer.  Error Details: Invalid json. at..." and then goes on to list several pieces within the app.

### Power BI

Power BI Desktop version August 2023

### Steps to reproduce the behavior

1. Go to 'Inspect report'
2. Choose a .pbix file 
3. Error window pops up

**Comment by KaelDowdy** [comment]
I have a similar issue when comparing reports (screenshot attached).

My most recent version of the PBIX opens fine (Original Version), but I get an error when I choose an older version of the PBIX (Comparison Version).  I tried opening the older version as the "Original Version" and still got the error.  

FWIW:  I did install the prerequisite .NET Runtime 7.0.11 before installing PBI Explorer.

<img width="507" alt="Report Comparer Issue - Error Opening File" src="https://github.com/tabulartools/pbi-explorer/assets/96840983/0286be21-4071-44fa-bfce-1a08a578fc76">

**Comment by DBojsen** [comment]
Hi @jhartranft 

To identify if this is because of a known issue or something else, we need to see the rest of the errormessage.
Could you please add that as a comment?

BR David - Tabular Tools

**Comment by DBojsen** [comment]
Hi @KaelDowdy 

This issue has hit a lot of people - I'll merge a few other bugs into this one and then give a shared answer to all of them.

BR David - Tabular Tools

**Comment by DBojsen** [comment]
Hi all

You have all been having issues related to deserialization of filters (both basic and advanced).
We'll address these issue this way:

**Short term (=days)**
- Handle these issues more gracefully
- Allow the report to still be deserialized, but some info on the impacted filters will (probably) be missing
- Introduce telemetry gathering, and send info about the filter types that has issues (without including any information related to the names of your report, tables, columns, measures etc) to our central telemetry repository.

**Longer term**
- Support 100% of the filters we can encounter in your reports in incremental steps using the telemetry to prioritise out efforts.

**Comment by DBojsen** [comment]
This have been fixed in version 0.3.1 (Beta2).  Please update by downloading the new version at www.PBIExplorer.com.
Thanks for reporting.

We will add the telemetry in next update
