### ISSUE TITLE
Error opening a pbix connected to AAS in "Direct Query" mode.

### ISSUE THREAD

**Issue by fahadkhan2306** [tabulartools/pbi-explorer#30]
### Describe the problem

Getting below error as I open the pbix which is connected to AAS in "Direct Query" mode.

<img width="508" alt="image" src="https://github.com/tabulartools/pbi-explorer/assets/51118866/3001e401-2e69-4586-a496-efbe054151eb">

----------------------
<img width="152" alt="image" src="https://github.com/tabulartools/pbi-explorer/assets/51118866/2d8baecc-b796-43b9-b2ea-f6564987076c">

### Power BI

2.122.325.0 64-bit (October, 2023)

### Windows

Windows 11 Enterprise

### Screenshots

<img width="508" alt="image" src="https://github.com/tabulartools/pbi-explorer/assets/51118866/d0f0cea6-bc79-4c30-8573-71c1cb96f691">
----------------------------------------------------

<img width="152" alt="image" src="https://github.com/tabulartools/pbi-explorer/assets/51118866/4f4aba90-da9d-4758-8a3d-6ea59728e4b3">

**Comment by DBojsen** [comment]
Hi @fahadkhan2306 

Is this on latest version (0.3.1) pf PBI Explorer?

**Comment by fahadkhan2306** [comment]
Hi @DBojsen Yes, using the latest version (0.3.1).
It appears to be an issue with reading advanced filters?

**Comment by DBojsen** [comment]
We'll get that fixed.

**Comment by DBojsen** [comment]
This should be fixed with BETA5 (0.6.1) which we released yesterday.
If you still have the issue, please reopen.

**Comment by fahadkhan2306** [comment]
Hi @DBojsen Tried with latest version released on 23rd Nov & I see this error now

<img width="566" alt="image" src="https://github.com/tabulartools/pbi-explorer/assets/51118866/c65520aa-756e-40cc-a463-89d321d06409">

**Comment by DBojsen** [comment]
Hi

This is probably because your report has sensitivity labels enabled.
This effectively encrypts the file and we have no way of reading it's content.

We should however provide a better error message - I have added that to the backlog.

Can you try a different report without sensitivity labels?

**Comment by fahadkhan2306** [comment]
Indeed this was due to sensitivity labels. I've tried on other report & it
worked. Thank you 👍
