### ISSUE TITLE
Visually indicate hovering and clicking for the items at the top of the side bar

### ISSUE THREAD

**Issue by Kenneth-Barber** [tabulartools/pbi-explorer#33]
### The feature request

In the side bar on the left, whether the side bar is expanded or collapsed, the expand/collapse button and the icons at the bottom visually change slightly when hovered over or clicked, but this does not happen with the items at the top. This makes it slightly more difficult to judge which item you are hovering over and forces the user to move their cursor more towards the middle of the item so that they are sure that they are clicking on the correct item, which is not the most user-friendly. This is also an inconsistency, both within the side bar itself and compared to what users are used to.

### Proposed solution

The solution is stated in the title. Copying the behaviour of the expand/collapse button and the icons at the bottom to the items at the top should suffice. Be sure to check that this behaviour applies both when the side bar is expanded and when it is collapsed.

**Comment by DBojsen** [comment]
Makes sense - we'll add this

**Comment by DBojsen** [comment]
This has now been fixed in BETA3.
You can download this version here [https://pbiexplorer.com](https://pbiexplorer.com).

Thank you for reporting.
