### ISSUE TITLE
Submit pbiexplorer.com for HSTS preloading

### ISSUE THREAD

**Issue by Kenneth-Barber** [tabulartools/pbi-explorer#34]
### The feature request

This website (https://hstspreload.org/?domain=pbiexplorer.com) indicates that pbiexplorer.com is eligible for HSTS preloading but is not actually submitted for HSTS preloading.

### Proposed solution

Complete the submission of pbiexplorer.com for HSTS preloading here: https://hstspreload.org/?domain=pbiexplorer.com.

**Comment by danieleperilli** [comment]
Submitted, thanks for reporting it!
