### ISSUE TITLE
Revise the width of page tabs

### ISSUE THREAD

**Issue by Kenneth-Barber** [tabulartools/pbi-explorer#36]
### Describe the problem

In my Power BI file, the 1st page is called "❓" (without quotes). In the Report Inspector, in the Wireframe tab, the tab for this page is not wide enough to display the full character.

### PBI Explorer

0.3.1

### Power BI

Power BI Desktop (September 2023)

### Windows

Windows 11 Home 22H2

### Additional context

I have not tested whether this issue occurs only with the 1st page or any page. We also do not yet know which other characters or page names are affected by this issue.

### Screenshots

<img width="11" alt="❓ Page Tab" src="https://github.com/tabulartools/pbi-explorer/assets/17665493/c2578e82-5c30-4a29-af7e-a5d78654b053">

**Comment by otykier** [comment]
Thanks for reporting. Seem to be an issue whenever emojis are used in page names. We'll make sure that's fixed!

**Comment by DBojsen** [comment]
This has now been fixed in BETA3.
You can download this version here [https://pbiexplorer.com](https://pbiexplorer.com).

Thank you for reporting.
