### ISSUE TITLE
"&" in page names do not display

### ISSUE THREAD

**Issue by Kenneth-Barber** [tabulartools/pbi-explorer#37]
### Describe the problem

In the Report Inspector, in the Wireframe tab, any "&" in page names do not display. There is no substitute character for "&". It is as if the "&" was never part of the page name. The ideal solution is to display the "&", but the next best solution is to use a substitute character.

### PBI Explorer

0.3.1

### Power BI

Power BI Desktop (September 2023)

### Windows

Windows 11 Home 22H2

### Additional context

I do not know which other characters fail to display. Excel has a similar issue for displaying file names that contain "&", whether in the splash screen when you open Excel or in Excel's status bar.

**Comment by DBojsen** [comment]
We'll make sure to fix this.

**Comment by DBojsen** [comment]
This is fixed in BETA4 (0.5.1).  Get it at pbiexplorer.com.
