### ISSUE TITLE
Tofu in the Report Explorer

### ISSUE THREAD

**Issue by Kenneth-Barber** [tabulartools/pbi-explorer#38]
### Describe the problem

In the Report Inspector, in the Report Explorer tab, I use the "❓" character in the name of a page, but this character displays as tofu. Ideally, all characters would render properly. However, if that is unreasonable, then focus on emojis, picture-like characters, or other characters that would not be used in formal text. These characters are great for keeping the page names short, which makes the page tabs narrower, which lets you see more page tabs without scrolling. Some of these characters render as a coloured picture, which adds visual variety to the page names and makes each one stand out uniquely more easily. My point is that these characters are very useful in page names and so I would expect them to be somewhat pervasive, especially in Power BI files that have many pages.

Ideally, this issue would be solved without any intervention from the user. However, the next best solution is to document how the user can avoid seeing tofu. Ideally, the solution would be something easier and smaller than installing all of the Noto fonts.

### PBI Explorer

0.3.1

### Power BI

Power BI Desktop (September 2023)

### Windows

Windows 11 Home 22H2

### Additional context

I have not tested this issue in the Data Model Explorer tab. I also do not know which other characters fail to render correctly.

**Comment by DBojsen** [comment]
Hi @Kenneth-Barber 

Thabk you for all your feedback and also for splitting in separate issues. Makes it much easier to track. 
We’ll review each one and get back separately. 

BR David - Tabular Tools

**Comment by DBojsen** [comment]
We have reproduced this and it will be fixed in next update

**Comment by DBojsen** [comment]
This has now been fixed in BETA3.
You can download this version here [https://pbiexplorer.com](https://pbiexplorer.com).

Thank you for reporting.
