### ISSUE TITLE
Maintain the size of icons in the side bar when expanding and collapsing the side bar

### ISSUE THREAD

**Issue by Kenneth-Barber** [tabulartools/pbi-explorer#39]
### Describe the problem

When the side bar on the left is expanded or collapsed, the icons do not change size other than those for "Report issue" and "Suggest feature" under "Help". None of the icons should change size. Keep the larger version of these icons so that all of the icons are roughly the same size.

### PBI Explorer

0.3.1

### Power BI

Power BI Desktop (September 2023)

### Windows

Windows 11 Home 22H2

**Comment by DBojsen** [comment]
We'll make sure to get this fixed

**Comment by DBojsen** [comment]
This has now been fixed in BETA3.
You can download this version here [https://pbiexplorer.com](https://pbiexplorer.com).

Thank you for reporting.
