### ISSUE TITLE
Error opening a pbix: The file contains a feature not yet supported

### ISSUE THREAD

**Issue by DomAtGitHub** [tabulartools/pbi-explorer#40]
### Describe the problem

When I open a pbix file which incorporates a single page which is empty I get the error message:
We couldn't open the specific file. Most likely, the file contains a feature not yet supported by PBI Explorer. 
More Details >see Screenshot.
Anyway, the file is empty because it's a dataset. I have another file which also consist of just one empty page and it works. 
Thus, I don't know what is different at the one file which produces the error

### PBI Explorer

0.3.1

### Power BI

2.121.942.0 64-bit (September 2023)

### Windows

Windows 10 Enterprise Version 10.0.19045 Build 19045

### Steps to reproduce the behavior

1. Open PBI Explrorer
2. Inspect report
3. Choose file from local disk
4. Error message

### Screenshots

![grafik](https://github.com/tabulartools/pbi-explorer/assets/42666679/fb471588-71a8-4746-9f87-035d9f0ef7bc)

**Comment by DBojsen** [comment]
We'll get that fixed

**Comment by DBojsen** [comment]
We'll make sure to handle this gracefully in the future

**Comment by DBojsen** [comment]
This has now been fixed in BETA3.
You can download this version here [https://pbiexplorer.com](https://pbiexplorer.com).

Thank you for reporting.
