### ISSUE TITLE
Speed up or eliminate the expand/collapse animation of the side bar

### ISSUE THREAD

**Issue by Kenneth-Barber** [tabulartools/pbi-explorer#41]
### Describe the problem

When you expand or collapse the side bar on the left, the sliding animation is slow and choppy and you can even see an intermediate/temporary "…" icon at the bottom. My guess is that the side bar tries to render each time one of the bottom icons changes position.

If you want to keep the sliding animation, please make it smoother. If the issue is the constant switching between rendering and moving icons, then move all of the icons first and then start the animation in the case of collapsing, and, in the case of expanding, move the icons only when the sliding animation has finished.

Alternatively, you could also eliminate the sliding animation.

### PBI Explorer

0.3.1

### Power BI

Power BI Desktop (September 2023)

### Windows

Windows 11 Home 22H2

### Additional context

I am using a computer that has an Intel Core i5-1145G7 processor and 64 GB of RAM. In other words, it is fairly new and pretty good, but it is not what you would consider to be a developer computer or a gaming computer, and it is almost certainly worse than what the developers at Tabular Tools are using. Other people who use PBI Explorer might be using even worse computers, so things might lag for them that do not lag for you.

**Comment by otykier** [comment]
Yeah, I agree the animation is annoying. We'll remove it.

**Comment by DBojsen** [comment]
This has now been fixed in BETA3.
You can download this version here [https://pbiexplorer.com](https://pbiexplorer.com).

Thank you for reporting.
