### ISSUE TITLE
"Visuals per page" number seems to be incorrect

### ISSUE THREAD

**Issue by Kenneth-Barber** [tabulartools/pbi-explorer#42]
### Describe the problem

In the Report Inspector, in the Summary tab, I see the following numbers:
Pages: 17
Visuals (total): 81
Visuals per page: 4.0

Assuming that "Visuals per page" means "Average visuals per page" (please clarify), then I would expect this to be calculated as 81 visuals ÷ 17 pages, which equals roughly 4.8 and not 4.0. I don't know if slicers are excluded or if pages that do not have visuals are excluded. If the "Visuals per page" number is being calculated incorrectly, then this needs to be fixed, but if the "Visuals per page" number is being calculated correctly, then it should be clarified which visuals and pages are included in or excluded from the calculation of this number.

### PBI Explorer

0.3.1

### Power BI

Power BI Desktop (September 2023)

### Windows

Windows 11 Home 22H2

**Comment by DBojsen** [comment]
The summary view will change a lot in the near future and we'll make sure to test the info we display there.
The visuals per page will be removed, so I will close this issue for now.
