### ISSUE TITLE
Data model Explorer tab show measures incorrect

### ISSUE THREAD

**Issue by JNTheunissen** [tabulartools/pbi-explorer#43]
### Describe the problem

In the Report inspector of the "PBI explorer" version 0.3.1.
The "Data model Explorer" tab shows  some of the measures but not all.
My "_measure" table has 57 measures all grouped in displayfolders.
The "Data model Explorer" tab shows 17 of the 57 measures.
These measures are grouped in display folders, two levels deep.
The first level only contains display folders and no measures.

I expected to see all the measures as defined in the "_measure" table.
 

### PBI Explorer

0.3.1 beta

### Power BI

Version: 2.121.903.0 64-bit (September 2023)

### Windows

Windows 11 Enterprise 22H2

### Screenshots

PowerBi screenshot
![image](https://github.com/tabulartools/pbi-explorer/assets/139467352/00786eed-526a-421b-901c-51dd6adb89f4)
PBI Explorer screenshot
![image](https://github.com/tabulartools/pbi-explorer/assets/139467352/b9a84af4-0ef1-4997-bce9-dae34fd71228)

**Comment by mthierba** [comment]
This is by design: The PBI Explorer _Data Model Explorer_ only displays an inferred data model, from the point of view of the report - only model elements directly referenced from within the report are shown. PBI Explorer (currently) does not access any model metadata that may be present in your PBIX/PBIP.

**Comment by JNTheunissen** [comment]
Thanks for your fast reply.
This would be great if the datamodel could be inferred from the report page.
Than it would be possible to see which measure is used in each page.
The "Data model Explorer" tab could be placed next to "Properties"and the "JSON" tab on the "Wireframe" Page
