### ISSUE TITLE
Feature to control (Show/hide) filter pane per page

### ISSUE THREAD

**Issue by akhilduvvuru** [tabulartools/pbi-explorer#44]
### The feature request

Problem Statement: We are passing a filter through a URL parameters which is working perfect. However, once the report is open, then I'm seeing that the parameterized field (in URL) in filter pane and also users are having option to edit/change the value.
 
Proposed Solution: It would be helpful if we are able to control the filter pane (Show/hide) by page especially in this use case of passing filters through URL Parameters. Or should be able to lock/hide the filters in filter pane which are passing through the URL parameters. Because in some cases we have other filters which need to be enabled for users. In this scenario if we disable to filter pane then all the filters will be hidden.

### Proposed solution

Problem Statement: We are passing a filter through a URL parameters which is working perfect. However, once the report is open, then I'm seeing that the parameterized field (in URL) in filter pane and also users are having option to edit/change the value.
 
Proposed Solution: It would be helpful if we are able to control the filter pane (Show/hide) by page especially in this use case of passing filters through URL Parameters. Or should be able to lock/hide the filters in filter pane which are passing through the URL parameters. Because in some cases we have other filters which need to be enabled for users. In this scenario if we disable to filter pane then all the filters will be hidden.

**Comment by DBojsen** [comment]
Hi @akhilduvvuru 

This sounds like feedback you should send to Microsoft.
We cannot control how Power BI or Power BI Desktop displays your report.

If I'm misunderstanding your feedback, please provide more context.

**Comment by akhilduvvuru** [comment]
Hi @DBojsen 

I completely understand and agree. However, I'm writing to you to understand if this can be possible using our PBI-Explorer (Like how we can control few things using Tabular Editor by connecting using XMLA end-point).
Thanks!

**Comment by DBojsen** [comment]
PBI Explorer is read-only - it is not supported by Microsoft to modify the report definition.

**Comment by akhilduvvuru** [comment]
Got it. Thanks for the response!
