### ISSUE TITLE
Documenting reports

### ISSUE THREAD

**Issue by rakshanNagesh0526** [tabulartools/pbi-explorer#45]
### The feature request

Is there a feature to document reports, does not have to be exquisite, but it should create a word doc, which developers can use to show everything about the report in one place

### Proposed solution

Exportable in word doc or excel, which can be used to help business users understand how to use it

**Comment by DBojsen** [comment]
This has already been suggested and answered here #25

**Comment by DBojsen** [comment]
Duplicate of #25

**Comment by DBojsen** [comment]
Duplicate of #25
