### ISSUE TITLE
Feature - Identify data model items not used in report

### ISSUE THREAD

**Issue by joe-smith-powerbi** [tabulartools/pbi-explorer#47]
### The feature request

Please include the ability to identify data model items (columns, measures, etc.) not used in the report. This will assist in removing unnecessary items from the data model, creating a more efficient data model. 

### Proposed solution

Implementation ideas:
- In Report Inspector\Data Model Explorer panel, add a "highlight usage" checkbox. When checked, the explorer list highlights each row that is not bound to any report object.
- In Report Inspector\Data Model Explorer panel, add a "highlight usage" checkbox. When checked, the explorer list adds column to panel with icon identifying rows not bound to any report object.
- Report Analyzer; if results are displayed similarly to the Best Practice Analyzer, then as a "Objects in data model not used in report visuals" node, with items listed underneath.

Bonus points:
- Ability to export results to JSON\Excel\plain text
- Ability to update data model (annotation or extended property) with status
- add different levels of non-usage; green/blue/OK for "displayed on visual", yellow/gray/Warning for "used in report visual, but not displayed", red/white/Fail for "not used in any report visuals". 

### Additional context

I was unable to find a roadmap, so I do not know if this is a planned feature or not.

**Comment by DBojsen** [comment]
Hi @joe-smith-powerbi 

So far, we are only working with the inferred/conceptual data model, which only contains the elements currently in use by the report. We are not working with the actual data model.  You will also see that things like display folders is not shown, as they are not available in the conceptual data model.
Therefore, anything shown IS in use by the report, if not, it would be removed.

We do have plans to also somehow use the actual datamodel, if you are opening a "thick" report, that also contain the model.bim, but if working with "thin" reports, that connect to a remote dataset, we have no way of displaying info about it.

> Ability to export results to JSON\Excel\plain text

This is already covered in #25 

> Ability to update data model (annotation or extended property) with status

This is not meant be a tool for editing the datamodel, use Tabular Editor for that

> add different levels of non-usage; green/blue/OK for "displayed on visual", yellow/gray/Warning for "used in report visual, but not displayed", red/white/Fail for "not used in any report visuals".

This is an extremely complex area, as one dataset can be used by multiple Power BI Reports, Power BI Paginated Reports, Excel files, 3rd party tools etc. - no immediate plans to cover this

**Comment by joe-smith-powerbi** [comment]
Hi @DBojsen , thanks for the quick response.
> So far, we are only working with the inferred/conceptual data model, which only contains the elements currently in use by the report. We are not working with the actual data model. 

So if I understand correctly, you are building the Data Model Explorer list based on the visual content only? For example, my data model has 3 measures, and I use 2 of them in report visuals; you're saying the third measure is not in the Data Model Explorer, because it's not included in a visual? 

> > Ability to export results to JSON\Excel\plain text

> This is already covered in #25

#25 is generic/ for the entire report set; this feature would export specific items from the list. Also, this was bonus points/nice to have, not the primary goal of my request.

> > Ability to update data model (annotation or extended property) with status

> This is not meant be a tool for editing the datamodel, use Tabular Editor for that

The thought here was once the fields were identified in PBI Explorer, Tabular Editor could take over and address the fields as needed. Again, not the main purpose of my request, just a nice feature.
 
> > add different levels of non-usage; green/blue/OK for "displayed on visual", yellow/gray/Warning for "used in report visual, but not displayed", red/white/Fail for "not used in any report visuals".

> This is an extremely complex area, as one dataset can be used by multiple Power BI Reports, Power BI Paginated Reports, Excel files, 3rd party tools etc. - no immediate plans to cover this

To be 100% clear, the core of my feature request is, "I want to to know what stuff in the data model that is not being used in this report." Nowhere do I say "remove the unused fields", and should not be interpreted that way. 
I know that a data model can be referenced by multiple reports, and agree that's a complex analysis; but I only care about the report I currently have open in PBI Explorer, not the others. I want your tool to help me identify potential issues in my report, not fix them for me.

**Comment by DBojsen** [comment]
@joe-smith-powerbi thank you for clarifying.

> So if I understand correctly, you are building the Data Model Explorer list based on the visual content only? For example, my data model has 3 measures, and I use 2 of them in report visuals; you're saying the third measure is not in the Data Model Explorer, because it's not included in a visual?

That is almost correct, except we are not building the inferred data model.  It is included in the report definition from Power BI, so we just expose what is already in the file.  But yes, it only contains references to the parts of the datamodel that is actually used.

> #25 is generic/ for the entire report set; this feature would export specific items from the list. Also, this was bonus points/nice to have, not the primary goal of my request.

#25 is used to track anything related to exporting from the tool.  We so far only have ideas, and no committed roadmap items in this area.

> The thought here was once the fields were identified in PBI Explorer, Tabular Editor could take over and address the fields as needed. Again, not the main purpose of my request, just a nice feature.

I think we are almost on the same page here - PBI Explorer can be used to clarify what is used in the data model, and then TE can take over to use that information to help you optimize the model.
This is a great vision, and something we would like to do sometime in the future, but it is not on current roadmap.

> To be 100% clear, the core of my feature request is, "I want to to know what stuff in the data model that is not being used in this report." Nowhere do I say "remove the unused fields", and should not be interpreted that way. I know that a data model can be referenced by multiple reports, and agree that's a complex analysis; but I only care about the report I currently have open in PBI Explorer, not the others. I want your tool to help me identify potential issues in my report, not fix them for me.

I probably read too much between the lines, and added my own thoughts and feelings towards the subject.
We have been talking *a lot* about this topic internally, but have no committed roadmap items (yet at least) to address this area.

**Comment by bkundrat** [comment]
I stumbled up on this request because I was looking for the same feature and was going to suggest it.

@DBojsen ... don't you have access to the local measures in the thin report to know whether any of those measures are or are not used in any of the visuals?

I just wanted to make sure I was following so please correct me where I'm off. Thanks!

**Comment by DBojsen** [comment]
Hi @bkundrat 

Missed your comment here - we do not.
We would need to parse the .bim file or connect to the remote model to learn which measures are available.
