### ISSUE TITLE
Misc Card - Numbers are cutted

### ISSUE THREAD

**Issue by ferdcoz** [tabulartools/pbi-explorer#48]
### Describe the problem

The numbers displayed at the Misc card are shown but cutted at the second digit.

### PBI Explorer

0.4.1

### Power BI

Power BI Desktop version July 2023

### Windows

Windows 10 Enterprise 21H2

### Steps to reproduce the behavior

1. Open PBI Explorer
2. Open report
3. Wait until rendering is complete

### Screenshots

![PBI_Explorer_MISC](https://github.com/tabulartools/pbi-explorer/assets/62630211/a7cf49e2-b45c-425d-bf76-511e2334c070)

**Comment by DBojsen** [comment]
Hi @ferdcoz 

Thanks for reporting - we'll get that fixed

**Comment by DBojsen** [comment]
This is fixed in BETA4 (0.5.1).  Get it at pbiexplorer.com.
