### ISSUE TITLE
Best Practice Issues Groups

### ISSUE THREAD

**Issue by fernandocalero** [tabulartools/pbi-explorer#55]
### The feature request

In Report Inspector panel the Issues are classified as:
- Severe
- Medium
- Low

But in  Report Analyzer they appear as:
- Error
- Warning
- (here I don't have an item so I don't know how it's called)

Cheers,
Fernando

### Proposed solution

I suggest they are called the same everywhere.

### Additional context

![figure1](https://github.com/tabulartools/pbi-explorer/assets/3391678/9ea8cf0f-518f-4bff-ba84-4ae7b1e70e93)
![figure2](https://github.com/tabulartools/pbi-explorer/assets/3391678/0233a704-0533-4950-b12f-fb08637d2466)

**Comment by DBojsen** [comment]
Hi @fernandocalero 

Completely agree and thank you for reporting.
To be frank, we changed it to Info, Warning, Error last minute before releasing, and didn't change everywhere.

We'll get that fixed

**Comment by DBojsen** [comment]
This is fixed with BETA5 (0.6.1) which we released yesterday.
