### ISSUE TITLE
We couldn't open the specified file. Most likely, the file contains a feature not yet supported by PBI Explorer

### ISSUE THREAD

**Issue by gizmoboy85** [tabulartools/pbi-explorer#56]
### Describe the problem

When I want to open a complex dashboard file, I get the following error message: "We couldn't open the specified file. Most likely, the file contains a feature not yet supported by PBI Explorer". Although I can open another file which is very simple but uses the same data source as the complex file.

### PBI Explorer

0.5.1

### Power BI

Power BI Desktop for PBI RS 2.121.903.0 64-bit (September 2023)

### Windows

Windows 11 Pro 22H2

### Steps to reproduce the behavior

1. Click on 'Inspect report'
2. Select Power BI report
3. Click on 'Open'
4. Error message with OK button pops up

### Screenshots

![image](https://github.com/tabulartools/pbi-explorer/assets/101334894/243923e9-e179-47d3-be67-77fb0301e652)

**Comment by DBojsen** [comment]
Hi @gizmoboy85 

Sorry about that.  We have a fix ready and hope to deploy a new version next week.
