### ISSUE TITLE
Spelling mistake: practive

### ISSUE THREAD

**Issue by Kenneth-Barber** [tabulartools/pbi-explorer#58]
### Describe the problem

In the bottom left corner, hover over the Report Analyzer. In the tooltip, "practive" should be "practice".

### PBI Explorer

0.5.1

### Power BI

Irrelevant

### Windows

Irrelevant

**Comment by DBojsen** [comment]
Good catch - we'll get that fixed

**Comment by DBojsen** [comment]
This is fixed with BETA5 (0.6.1) which we released yesterday.
