### ISSUE TITLE
In the Report Analyzer, expand "Sev." to "Severity"

### ISSUE THREAD

**Issue by Kenneth-Barber** [tabulartools/pbi-explorer#59]
### Describe the problem

In the Report Analyzer, please rename the "Sev." column to "Severity". "Severity" is only slightly longer than the contents of the column but is much clearer.

### PBI Explorer

0.5.1

### Power BI

Irrelevant

### Windows

Irrelevant

**Comment by DBojsen** [comment]
Agreed - we'll change that.

**Comment by DBojsen** [comment]
This is fixed with BETA5 (0.6.1) which we released yesterday.
