### ISSUE TITLE
In the Report Analyzer, move the "Expand all" and "Collapse all" buttons to the left

### ISSUE THREAD

**Issue by Kenneth-Barber** [tabulartools/pbi-explorer#60]
### The feature request

In the Report Analyzer, you can expand and collapse individual rules using the arrows to the left of the rules. However, the "Expand all" and "Collapse all" buttons, which do the same thing but for all rules, are way off to the right. This distance is even greater if you are using a large monitor.

### Proposed solution

Please move the "Expand all" and "Collapse all" buttons to the left so that they are closer to the arrows.

**Comment by DBojsen** [comment]
We'll probably add more buttons to this menubar, and when doing that we'll try to find the best positions for everything.
But it seems like a good idea to have them close to the regular expand/collapse buttons.

Now that I think about it, we should probably also use the same icon.

**Comment by DBojsen** [comment]
This is fixed with BETA5 (0.6.1) which we released yesterday.
We're still working on the final UI for Report Analyzer, so it might change in later versions.
