### ISSUE TITLE
Revise the appearance of the "Expand all" and "Collapse all" buttons in the Report Analyzer

### ISSUE THREAD

**Issue by Kenneth-Barber** [tabulartools/pbi-explorer#61]
### Describe the problem

In the Report Analyzer, the "Expand all" and "Collapse all" buttons look blurry. When you zoom in, it looks like anti-aliasing was applied to these small icons, which smudged their fine details. Please replace these icons with ones that do not look blurry. This could mean removing the anti-aliasing from these icons or using entirely different icons, even if they do not resemble the current ones.

### PBI Explorer

0.5.1

### Power BI

Irrelevant

### Windows

Windows 11 Home 22H2, 22621.2506

### Screenshots

<img width="342" alt="Expand All   Collapse All (12× Zoom)" src="https://github.com/tabulartools/pbi-explorer/assets/17665493/abcd0242-6327-4700-a81b-e21229e0d565">

**Comment by DBojsen** [comment]
Hi

We'll see what we can do.

**Comment by DBojsen** [comment]
This should be fixed with BETA5 (0.6.1) which we released yesterday.
If you still have the issue, please reopen.
