### ISSUE TITLE
In the Report Analyzer, allow the "Type" column to expand wider

### ISSUE THREAD

**Issue by Kenneth-Barber** [tabulartools/pbi-explorer#62]
### Describe the problem

In the Report Analyzer, the maximum width of the "Type" column is not even wide enough to fully show some of its values, such as "Clustered Column". Please allow the "Type" column to expand widely enough to fully show the widest value that it can contain.

### PBI Explorer

0.5.1

### Power BI

Irrelevant

### Windows

Windows 11 Home 22H2, 22621.2506

### Screenshots

<img width="62" alt="Narrow Type Column" src="https://github.com/tabulartools/pbi-explorer/assets/17665493/e5d5c391-ee6d-4686-9fc8-cdc1bd1b877a">

**Comment by DBojsen** [comment]
Agreed - we'll fix.

**Comment by DBojsen** [comment]
This should be fixed with BETA5 (0.6.1) which we released yesterday.
If you still have the issue, please reopen.
