### ISSUE TITLE
Spelling mistake: aboid

### ISSUE THREAD

**Issue by Kenneth-Barber** [tabulartools/pbi-explorer#63]
### Describe the problem

In the Help, in the tooltips of "Report issue" and "Suggest feature", "aboid" should be "avoid".

### PBI Explorer

0.5.1

### Power BI

Irrelevant

### Windows

Irrelevant

**Comment by DBojsen** [comment]
Good catch, thank you.

**Comment by DBojsen** [comment]
This is fixed with BETA5 (0.6.1) which we released yesterday.
