### ISSUE TITLE
In the Report Comparer, indicate when the "Click to open" text is clickable

### ISSUE THREAD

**Issue by Kenneth-Barber** [tabulartools/pbi-explorer#65]
### The feature request

At the top of the Report Comparer, there is text that says "(Click to open original report)" and "(Click to open comparison report)". However, it is not clear when this text is clickable.

### Proposed solution

Please give some indication of when the cursor is in range to be able to click on this text. This could mean, for example, formatting the text or the area around it or changing the cursor.

**Comment by DBojsen** [comment]
Makes sense - we'll fix

**Comment by DBojsen** [comment]
This should be fixed with BETA5 (0.6.1) which we released yesterday.
If you still have the issue, please reopen.
