### ISSUE TITLE
In the Report Analyzer, allow the rightmost column to be resized

### ISSUE THREAD

**Issue by Kenneth-Barber** [tabulartools/pbi-explorer#66]
### The feature request

In the Report Analyzer, the rightmost column (currently "Category") cannot be resized. If you are using a large screen, this places the filter icon far from the name and values of the column.

### Proposed solution

Please allow the rightmost column to be resized so that the filter icon can be brought closer to the action.

**Comment by DBojsen** [comment]
We'll get that fixed

**Comment by DBojsen** [comment]
This should be fixed with BETA5 (0.6.1) which we released yesterday.
If you still have the issue, please reopen.
