### ISSUE TITLE
PBI explorer outdated version error

### ISSUE THREAD

**Issue by ricky7uio** [tabulartools/pbi-explorer#89]
### Describe the problem

Getting this error when opening the app:
![image](https://github.com/tabulartools/pbi-explorer/assets/44656050/49e53519-31a2-4367-a03c-04ba40cf5ecd)

The latest version I see is the same:
![image](https://github.com/tabulartools/pbi-explorer/assets/44656050/59afab74-e777-4ae6-9b59-46698c51accd)

### PBI Explorer

0.7.1

### Power BI

is not related to PBI

### Windows

Windows 10

### Steps to reproduce the behavior

1 open Pbi explorer

**Comment by ricky7uio** [comment]
BTW, I think it is not the best that we can't use at all the app when you release a new version.

**Comment by PJandLiz** [comment]
I've just had the same problem 😣

**Comment by NivethTX** [comment]
I have the same problem too.

**Comment by DBojsen** [comment]
Hi all

We'll get this fixed asap.  It is an intentional kill switch hardcoded in the app to avoid old beta versions in the wild.
But we failed to release an updated version with a new deadline for the kill switch.
Should be ready within the hour.

/ David - Tabular Tools

**Comment by DBojsen** [comment]
Hi all

A new version (0.7.2) is now available.
We're sorry for the trouble.

**Comment by ricky7uio** [comment]
Thank you very much!!
