### ISSUE TITLE
Downloaded on Friday. Error message: "PBI Explorer version outdated"

### ISSUE THREAD

**Issue by awecamus** [tabulartools/pbi-explorer#90]
### Describe the problem

Hello.
This is an error related to PBI Explorer. The version downloaded from the website PbiExplorer-Net7-0.7.1 it doesn't run. The application is showing 
"PBI Explorer version outdated. This version of PBI Explorer is outdated, Please go to the website bla bla and update. 
So, This is the version just downloaded. Why it's not working?
Thanks,

### PBI Explorer

PbiExplorer-Net7-0.7.1

### Power BI

Dec 2023

### Windows

11

### Steps to reproduce the behavior

x

### Additional context

x

### Screenshots

![image](https://github.com/tabulartools/pbi-explorer/assets/159004362/5120aa63-1922-4ea3-9126-d7947e4fc900)

### Anything else ?

x

**Comment by DBojsen** [comment]
Hi @awecamus 

You need to download 0.7.2.  0.7.1 is no longer functional.
See #89 

Best Regards

David, Tabular Tools

**Comment by poujor** [comment]
Hi,

Today 1. Aug 2025 I have the same issue on Version: 0.7.3 (2024-08-02), just downloaded.
I don't understand why your applications can state it is outdated, when it is the newest available.

Best Regards 
Poul

**Comment by DBojsen** [comment]
Hi @poujor 

Sorry about that - a new version without the time-based kill switch has been deployed.
We have stopped active development on the PBI Explorer, but are working on releasing the C# Object Model for Power BI Reports as open source to support other projects.

/ David - Tabular Tools
