### ISSUE TITLE
update Required and No update available

### ISSUE THREAD

**Issue by muhssamy** [tabulartools/pbi-explorer#97]
### Describe the problem

i am facing this problem while opening the pbi-explorer

![image](https://github.com/user-attachments/assets/f549c153-95de-45c5-b4d5-d0054e30fd86)

and when I try to download new version there is no new avilable
![image](https://github.com/user-attachments/assets/3779ad93-66f9-4f4e-b400-0c9f2a97d274)

it was working with me yesterday and stopped today

### PBI Explorer

0.7.2

### Power BI

Power BI Desktop version July 2024

### Windows

Windows 10 Enterprise,22H2

**Comment by DBojsen** [comment]
Hi @muhssamy 

Sorry about that - I have uploaded a new version.

BR David - Tabular Tools
